---
title: "atlantic_camera_trap_mammals - Camera trap surveys of Atlantic Forest mammals: A data set for analyses considering imperfect detection (2004–2020)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{atlantic_camera_trap_mammals - Camera trap surveys of Atlantic Forest mammals: A data set for analyses considering imperfect detection (2004–2020)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### Dataset used

- [`atlantic_camera_trap_mammals`](https://mauriciovancine.github.io/atlanticr/reference/atlantic_camera_trap_mammals.html)

# Introduction

The [`atlantic_camera_trap_mammals`](https://mauriciovancine.github.io/atlanticr/reference/atlantic_camera_trap_mammals.html) dataset contains 

# Data exploration

# Citations

Franceschi et al. 2024. ATLANTIC-CAMTRAPS: a dataset of medium and large terrestrial mammal communities in the Atlantic Forest of South America. *Ecology*, 105(5), e4298. https://doi.org/10.1002/ecy.4298

# How we processed the raw data

Download data from Ecology

```{r eval=FALSE}
# download
# download data from https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.1998

# unzip
unzip(zipfile = "data-raw/ecy1998-sup-0001-datas1.zip", exdir = "data-raw")
```

Data cleaning
```{r eval=FALSE}
# download
# download data from https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.4298

# download
download.file(url = "https://figshare.com/ndownloader/files/41311500",
              destfile = "data-raw/DATASET_CAMTRAP_SURVEYS_ATLANTICFOREST.csv", mode = "wb")

download.file(url = "https://figshare.com/ndownloader/files/41311503",
              destfile = "data-raw/DATASET_CAMTRAP_RECORDS_ATLANTICFOREST.csv", mode = "wb")

# import data
atlantic_camera_trap_mammals_surveys <- readr::read_delim("data-raw/DATASET_CAMTRAP_SURVEYS_ATLANTICFOREST.csv", delim = ";")
atlantic_camera_trap_mammals_surveys

atlantic_camera_trap_mammals_records <- readr::read_delim("data-raw/DATASET_CAMTRAP_RECORDS_ATLANTICFOREST.csv", delim = ";")
atlantic_camera_trap_mammals_records

# save data
usethis::use_data(atlantic_camera_trap_mammals_surveys, overwrite = TRUE)
usethis::use_data(atlantic_camera_trap_mammals_records, overwrite = TRUE)

# delete files
unlink("data-raw/DATASET_CAMTRAP_RECORDS_ATLANTICFOREST.csv")
unlink("data-raw/DATASET_CAMTRAP_SURVEYS_ATLANTICFOREST.csv")
```
